# Generated by Django 4.2.7 on 2023-11-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_survey_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='creation_date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='survey',
            name='slug',
            field=models.SlugField(default='primer', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
