# Generated by Django 4.2.7 on 2023-12-05 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_alter_survey_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created'], 'permissions': (('view_own_survey', 'Can view own survey'),)},
        ),
    ]
