# Generated by Django 4.2.7 on 2023-12-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_alter_survey_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('edit_own_question', 'Can edit own question'),)},
        ),
    ]
