# Generated by Django 4.2.7 on 2023-12-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('view_own_question', 'Can view own question'), ('edit_own_question', 'Can edit own question'))},
        ),
    ]
