# Generated by Django 4.2.7 on 2023-12-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created'], 'permissions': (('view_own_survey', 'Can view own survey'), ('edit_own_survey', 'Can edit own survey'), ('delete_own_survey', 'Can delete own survey'))},
        ),
    ]
