# Generated by Django 4.2.7 on 2023-12-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_alter_survey_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('view_own_question', 'Can view own question'), ('edit_own_question', 'Can edit own question'), ('delete_own_question', 'Can delete own question'))},
        ),
    ]
